export const ADD_ITEM = 'ADD_ITEM'
export const REQUEST_ITEMS = 'REQUEST_ITEMS'
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS'

export const ADD_USER = 'ADD_USER'
export const REQUEST_USER_LOGIN = 'REQUEST_USER_LOGIN'
export const RECEIVE_USER_LOGIN = 'RECEIVE_USER_LOGIN'
export const ERROR_USER_LOGIN = 'ERROR_USER_LOGIN'